name: PR Checks
env:
  HUSKY: 0

on:
  workflow_dispatch:
  pull_request:

jobs:
  pr-checks:
    strategy:
      fail-fast: true

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - uses: biomejs/setup-biome@a9763ed3d2388f5746f9dc3e1a55df7f4609bc89 # v2.5.1
        with:
          version: latest

      - name: Install dependencies
        working-directory: ./
        run: |
          npm ci

      - name: Run linter
        working-directory: ./
        run: |
          biome ci .

      - name: Run type checker
        working-directory: ./
        run: |
          npm run ts

      - name: Run tests
        working-directory: ./
        run: |
          npm run test

      - name: Build
        working-directory: ./
        run: |
          npm run build
